### ISSUE TITLE
Document target users aka why this instead of X, Y, Z?

### ISSUE THREAD

**Issue by hyiltiz** [itchyny/miv#13]
There are a few alternatives to this, some old and some new, and in various languages. How does this compare to the rest, i.e. from a users' perspective, which users would want to choose this over the alternatives?

**Comment by itchyny** [comment]
Currently there are great managers so I don't recommend others to use this plugin manager. But [I still use this](https://github.com/itchyny/dotfiles/blob/a7d75b2/.vimrc.yaml) and I target only me so I don't write to the README for this kind of explanation. Long ago (miv was developed 6 years ago, vim-plug did not exist), Vim plugin managers introduced painful overhead on startup of Vim and I wanted a transpiler to generate the fast plugin loader in Vim script. Configuring the lazy loading of neobundle.vim was painful for me too. I manage plugin configurations apart from .vimrc in declarative fashion in YAML (which inspired dein.vim for TOML loader, I believe). Installation is easy due to Homebrew but development is painful because I don't write Haskell these days. [Volt](https://github.com/vim-volt/volt) is a good alternative, which is written in Golang.
